# Generated by Django 4.1.4 on 2022-12-16 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': False, 'ordering': ['category_id']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False, 'ordering': ['product_id']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False, 'ordering': ['user_id']},
        ),
    ]
