# Generated by Django 4.1.4 on 2022-12-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('shoppingCart_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('num', models.IntegerField()),
            ],
            options={
                'db_table': 'shoppingCart',
                'ordering': ['shoppingCart_id'],
                'managed': False,
            },
        ),
    ]
