# Generated by Django 4.1.4 on 2022-12-29 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_author_rating_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating_author',
            options={'managed': False, 'ordering': ['rating_id']},
        ),
        migrations.AlterModelTable(
            name='rating_author',
            table='rating_author',
        ),
    ]
