# Generated by Django 3.0.3 on 2023-03-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_rating_author_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating_Star',
            fields=[
                ('rating_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('rating', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rating_star',
                'ordering': ['rating_id'],
                'managed': False,
            },
        ),
    ]
